In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as pl
import seaborn as sns

%matplotlib inline

C:\Users\RAHUL\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [29]:
df = pd.read_csv("F:\\STUDY MATERIAL\\MACHINE LEARNING\\DATASETS\\titanic-data\\train_clean.csv")
df.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket Title  Family_Size  
0       3    male      1       0.0         A/5 21171    Mr            1  
1       1  female      1       1.0          PC 17599   Mrs            1  
2       3  female      0       1.0  STON/O2. 3101282  Miss            0  
3       1  female      1       1.0            113803   Mrs            1  
4       3    male      0       0.0            373450    Mr            0

In [30]:
test = pd.read_csv("F:\\STUDY MATERIAL\\MACHINE LEARNING\\DATASETS\\titanic-data\\test_clean.csv")
test.head()

Age Cabin Embarked     Fare                                          Name  \
0  34.5   NaN        Q   7.8292                              Kelly, Mr. James   
1  47.0   NaN        S   7.0000              Wilkes, Mrs. James (Ellen Needs)   
2  62.0   NaN        Q   9.6875                     Myles, Mr. Thomas Francis   
3  27.0   NaN        S   8.6625                              Wirz, Mr. Albert   
4  22.0   NaN        S  12.2875  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   

   Parch  PassengerId  Pclass     Sex  SibSp  Survived   Ticket Title  \
0      0          892       3    male      0       NaN   330911    Mr   
1      0          893       3  female      1       NaN   363272   Mrs   
2      0          894       2    male      0       NaN   240276    Mr   
3      0          895       3    male      0       NaN   315154    Mr   
4      1          896       3  female      1       NaN  3101298   Mrs   

   Family_Size  
0            0  
1            1  
2            0  
3            0  
4            2

In [31]:
df.isna().sum()

Age              0
Cabin          687
Embarked         0
Fare             0
Name             0
Parch            0
PassengerId      0
Pclass           0
Sex              0
SibSp            0
Survived         0
Ticket           0
Title            0
Family_Size      0
dtype: int64

In [32]:
df.drop('Cabin',axis ='columns', inplace = True)
test.drop('Cabin',axis ='columns', inplace = True)

In [33]:
df.drop('Name',axis ='columns', inplace = True)
df.drop('Ticket',axis ='columns', inplace = True)

test.drop('Name',axis ='columns', inplace = True)
test.drop('Ticket',axis ='columns', inplace = True)

In [34]:
df.head()

Age Embarked     Fare  Parch  PassengerId  Pclass     Sex  SibSp  \
0  22.0        S   7.2500      0            1       3    male      1   
1  38.0        C  71.2833      0            2       1  female      1   
2  26.0        S   7.9250      0            3       3  female      0   
3  35.0        S  53.1000      0            4       1  female      1   
4  35.0        S   8.0500      0            5       3    male      0   

   Survived Title  Family_Size  
0       0.0    Mr            1  
1       1.0   Mrs            1  
2       1.0  Miss            0  
3       1.0   Mrs            1  
4       0.0    Mr            0

In [35]:
test.head()

Age Embarked     Fare  Parch  PassengerId  Pclass     Sex  SibSp  \
0  34.5        Q   7.8292      0          892       3    male      0   
1  47.0        S   7.0000      0          893       3  female      1   
2  62.0        Q   9.6875      0          894       2    male      0   
3  27.0        S   8.6625      0          895       3    male      0   
4  22.0        S  12.2875      1          896       3  female      1   

   Survived Title  Family_Size  
0       NaN    Mr            0  
1       NaN   Mrs            1  
2       NaN    Mr            0  
3       NaN    Mr            0  
4       NaN   Mrs            2

In [36]:
df.shape

(891, 11)

In [37]:
df.replace({'male':1, 'female':0},inplace = True)
test.replace({'male':1, 'female':0},inplace = True)

In [38]:
df.head()

Age Embarked     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Survived  \
0  22.0        S   7.2500      0            1       3    1      1       0.0   
1  38.0        C  71.2833      0            2       1    0      1       1.0   
2  26.0        S   7.9250      0            3       3    0      0       1.0   
3  35.0        S  53.1000      0            4       1    0      1       1.0   
4  35.0        S   8.0500      0            5       3    1      0       0.0   

  Title  Family_Size  
0    Mr            1  
1   Mrs            1  
2  Miss            0  
3   Mrs            1  
4    Mr            0

In [39]:
test.head()

Age Embarked     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Survived  \
0  34.5        Q   7.8292      0          892       3    1      0       NaN   
1  47.0        S   7.0000      0          893       3    0      1       NaN   
2  62.0        Q   9.6875      0          894       2    1      0       NaN   
3  27.0        S   8.6625      0          895       3    1      0       NaN   
4  22.0        S  12.2875      1          896       3    0      1       NaN   

  Title  Family_Size  
0    Mr            0  
1   Mrs            1  
2    Mr            0  
3    Mr            0  
4   Mrs            2

In [40]:
#one hot encoding
dummies = pd.get_dummies(df['Title'])
df = pd.concat([df,dummies],axis='columns')
df.drop('Title',axis ='columns', inplace = True)

In [41]:
#one hot encoding
dummies = pd.get_dummies(test['Title'])
test = pd.concat([test,dummies],axis='columns')
test.drop('Title',axis ='columns', inplace = True)

In [42]:
#one hot encoding
dummies = pd.get_dummies(df['Embarked'])
df = pd.concat([df,dummies],axis='columns')
df.drop('Embarked',axis ='columns', inplace = True)

dummies1 = pd.get_dummies(test['Embarked'])
test = pd.concat([test,dummies1],axis='columns')
test.drop('Embarked',axis ='columns', inplace = True)

In [43]:
df.head()

Age     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Survived  \
0  22.0   7.2500      0            1       3    1      1       0.0   
1  38.0  71.2833      0            2       1    0      1       1.0   
2  26.0   7.9250      0            3       3    0      0       1.0   
3  35.0  53.1000      0            4       1    0      1       1.0   
4  35.0   8.0500      0            5       3    1      0       0.0   

   Family_Size  Dr  Master  Miss  Mr  Mrs  Rev  C  Q  S  
0            1   0       0     0   1    0    0  0  0  1  
1            1   0       0     0   0    1    0  1  0  0  
2            0   0       0     1   0    0    0  0  0  1  
3            1   0       0     0   0    1    0  0  0  1  
4            0   0       0     0   1    0    0  0  0  1

In [44]:
test.head()

Age     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Survived  \
0  34.5   7.8292      0          892       3    1      0       NaN   
1  47.0   7.0000      0          893       3    0      1       NaN   
2  62.0   9.6875      0          894       2    1      0       NaN   
3  27.0   8.6625      0          895       3    1      0       NaN   
4  22.0  12.2875      1          896       3    0      1       NaN   

   Family_Size  Dr  Master  Miss  Mr  Mrs  Rev  C  Q  S  
0            0   0       0     0   1    0    0  0  1  0  
1            1   0       0     0   0    1    0  0  0  1  
2            0   0       0     0   1    0    0  0  1  0  
3            0   0       0     0   1    0    0  0  0  1  
4            2   0       0     0   0    1    0  0  0  1

In [45]:
test.drop('Survived',axis = 'columns',inplace = True)
test.head()

Age     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Family_Size  Dr  \
0  34.5   7.8292      0          892       3    1      0            0   0   
1  47.0   7.0000      0          893       3    0      1            1   0   
2  62.0   9.6875      0          894       2    1      0            0   0   
3  27.0   8.6625      0          895       3    1      0            0   0   
4  22.0  12.2875      1          896       3    0      1            2   0   

   Master  Miss  Mr  Mrs  Rev  C  Q  S  
0       0     0   1    0    0  0  1  0  
1       0     0   0    1    0  0  0  1  
2       0     0   1    0    0  0  1  0  
3       0     0   1    0    0  0  0  1  
4       0     0   0    1    0  0  0  1

In [46]:
df.head()

Age     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Survived  \
0  22.0   7.2500      0            1       3    1      1       0.0   
1  38.0  71.2833      0            2       1    0      1       1.0   
2  26.0   7.9250      0            3       3    0      0       1.0   
3  35.0  53.1000      0            4       1    0      1       1.0   
4  35.0   8.0500      0            5       3    1      0       0.0   

   Family_Size  Dr  Master  Miss  Mr  Mrs  Rev  C  Q  S  
0            1   0       0     0   1    0    0  0  0  1  
1            1   0       0     0   0    1    0  1  0  0  
2            0   0       0     1   0    0    0  0  0  1  
3            1   0       0     0   0    1    0  0  0  1  
4            0   0       0     0   1    0    0  0  0  1

In [47]:
y = df['Survived']

In [48]:
y.head()

0    0.0
1    1.0
2    1.0
3    1.0
4    0.0
Name: Survived, dtype: float64

In [49]:
df.drop('Survived',axis = 'columns',inplace = True)

In [50]:
x = df
x.head()

Age     Fare  Parch  PassengerId  Pclass  Sex  SibSp  Family_Size  Dr  \
0  22.0   7.2500      0            1       3    1      1            1   0   
1  38.0  71.2833      0            2       1    0      1            1   0   
2  26.0   7.9250      0            3       3    0      0            0   0   
3  35.0  53.1000      0            4       1    0      1            1   0   
4  35.0   8.0500      0            5       3    1      0            0   0   

   Master  Miss  Mr  Mrs  Rev  C  Q  S  
0       0     0   1    0    0  0  0  1  
1       0     0   0    1    0  1  0  0  
2       0     1   0    0    0  0  0  1  
3       0     0   0    1    0  0  0  1  
4       0     0   1    0    0  0  0  1

In [53]:
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
scaler = MinMaxScaler()

#train
scaler.fit(x)
x = scaler.transform(x)

In [54]:
x = pd.DataFrame(x)
x.head()

0         1    2         3    4    5      6    7    8    9   10  \
0  0.271174  0.014151  0.0  0.000000  1.0  1.0  0.125  0.1  0.0  0.0  0.0   
1  0.472229  0.139136  0.0  0.001124  0.0  0.0  0.125  0.1  0.0  0.0  0.0   
2  0.321438  0.015469  0.0  0.002247  1.0  0.0  0.000  0.0  0.0  0.0  1.0   
3  0.434531  0.103644  0.0  0.003371  0.0  0.0  0.125  0.1  0.0  0.0  0.0   
4  0.434531  0.015713  0.0  0.004494  1.0  1.0  0.000  0.0  0.0  0.0  0.0   

    11   12   13   14   15   16  
0  1.0  0.0  0.0  0.0  0.0  1.0  
1  0.0  1.0  0.0  1.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  1.0  
3  0.0  1.0  0.0  0.0  0.0  1.0  
4  1.0  0.0  0.0  0.0  0.0  1.0

In [55]:
scaler.fit(test)
test = scaler.transform(test)

In [56]:
test = pd.DataFrame(test)
test.head()

0         1         2         3    4    5      6    7    8    9  \
0  0.452723  0.015282  0.000000  0.000000  1.0  1.0  0.000  0.0  0.0  0.0   
1  0.617566  0.013663  0.000000  0.002398  1.0  0.0  0.125  0.1  0.0  0.0   
2  0.815377  0.018909  0.000000  0.004796  0.5  1.0  0.000  0.0  0.0  0.0   
3  0.353818  0.016908  0.000000  0.007194  1.0  1.0  0.000  0.0  0.0  0.0   
4  0.287881  0.023984  0.111111  0.009592  1.0  0.0  0.125  0.2  0.0  0.0   

    10   11   12   13   14   15   16  
0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  1.0  0.0  0.0  0.0  1.0  
2  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
3  0.0  1.0  0.0  0.0  0.0  0.0  1.0  
4  0.0  0.0  1.0  0.0  0.0  0.0  1.0

In [57]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [58]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x,y)

C:\Users\RAHUL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [59]:
model.predict(x_test)

array([1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0.])

In [60]:
model.score(x_test,y_test)

0.8212290502793296

In [61]:
model.predict(test)

array([0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [62]:
model.score(x_train,y_train)

0.8398876404494382

In [92]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,model.predict(x_train)))
print(classification_report(y_train,model.predict(x_train)))

[[396  48]
 [ 66 202]]
              precision    recall  f1-score   support

         0.0       0.86      0.89      0.87       444
         1.0       0.81      0.75      0.78       268

    accuracy                           0.84       712
   macro avg       0.83      0.82      0.83       712
weighted avg       0.84      0.84      0.84       712



In [94]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,model.predict(x_test)))
print(classification_report(y_test,model.predict(x_test)))

[[92 13]
 [19 55]]
              precision    recall  f1-score   support

         0.0       0.83      0.88      0.85       105
         1.0       0.81      0.74      0.77        74

    accuracy                           0.82       179
   macro avg       0.82      0.81      0.81       179
weighted avg       0.82      0.82      0.82       179



In [63]:
from sklearn.neural_network import MLPClassifier

model_nn = MLPClassifier(solver = 'adam')

model_nn.fit(x_train,y_train)

C:\Users\RAHUL\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [64]:
model_nn.predict(x_test)

array([1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0.])

In [65]:
model_nn.score(x_test,y_test)

0.8100558659217877

In [89]:
model_nn.score(x_train,y_train)

0.8567415730337079

In [90]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,model_nn.predict(x_train)))
print(classification_report(y_train,model_nn.predict(x_train)))

[[411  33]
 [ 69 199]]
              precision    recall  f1-score   support

         0.0       0.86      0.93      0.89       444
         1.0       0.86      0.74      0.80       268

    accuracy                           0.86       712
   macro avg       0.86      0.83      0.84       712
weighted avg       0.86      0.86      0.85       712



In [91]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,model_nn.predict(x_test)))
print(classification_report(y_test,model_nn.predict(x_test)))

[[93 12]
 [22 52]]
              precision    recall  f1-score   support

         0.0       0.81      0.89      0.85       105
         1.0       0.81      0.70      0.75        74

    accuracy                           0.81       179
   macro avg       0.81      0.79      0.80       179
weighted avg       0.81      0.81      0.81       179



In [ ]:
#refer this site for more info.

https://www.kaggle.com/jamesleslie/titanic-neural-network-for-beginners/data